CI/CD: use self-hosted runner
Error: failed to run custom build command for `afl v0.12.12`
Caused by:
  process didn't exit successfully: `/home/runner/work/rust-spdm/rust-spdm/target/debug/build/afl-3cc9b5eed570967d/build-script-build` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.

Often have this error. The cause is unclear. Use self-hosted runner to avoid this issue.
Another advantage is that it can reduce the execution time.

Signed-off-by: xiaoyuxlu <xiaoyu1.lu@intel.com>